Enhancement/223 saf sdk to saf docs
StructuralAnalysisFormat/StructuralAnalysisFormat-Doc pull request #228
Opened 2022-09-19 14:26 UTC by msalak-scia

new part of documentation which should describe the usage of software development kit
it contains 4 new pages

2022-09-26 12:40 UTC, dschuermans commented
I might have phrased things wrong originally.
I did say you could use the markdown files from the nuget packages but looking at this now, it doesn't quite fit.

We'd need the following:
- [ ] Introduction page (what is the SDK, what is it used for)
- [ ] Available packages and their dependencies
- [X] Per package a page detailing what it does (which we have now)

2022-10-25 07:09 UTC, dschuermans requested changes
Please make the requested changes 😄

2022-10-25 07:09 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.md
> +This package implements the [Structural Analysis Format](https://www.saf.guide) in C#
The link here can be removed

2022-10-25 07:09 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.md
> +- Uses UnitsNet for unit operations
For each package, add a link to their respective nuget.org page

2022-10-25 07:09 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.md
> +  _If you wish to use SimpleInjector v5_
Add links here to the corresponding pages

2022-10-25 07:09 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Tests.Infrastructure.md
> +If the builder accepts actual units, you are free to provide it with units defined in the imperial system for example.
Turn this into one of those tip boxes

2022-10-25 07:09 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Tests.Infrastructure.md
> +So it may happen that some objects constructed by either the data builders or from the house model have weird values that do not make sense to a structural engineer.
Turn this into one of those tip boxes

2022-10-25 07:09 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Bootstrappers.SimpleInjector4.md
> +This package will bootstrap the internal components for you, using SimpleInjector v4
Add a link to the SimpleInjector 4 docs

2022-10-25 07:09 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Bootstrappers.SimpleInjector5.md
> +This package will bootstrap the internal components for you, using SimpleInjector v5
Add a link to the SimpleInjector 5 docs

2022-10-25 07:13 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.md
> +  _If you wish to use SimpleInjector v5_
v4: https://docs.simpleinjector.org/en/4.0/
v5: https://docs.simpleinjector.org/en/5.0/

2022-10-25 07:14 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Bootstrappers.SimpleInjector4.md
> +This package will bootstrap the internal components for you, using SimpleInjector v4
https://docs.simpleinjector.org/en/4.0/

2022-10-25 07:14 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Bootstrappers.SimpleInjector5.md
> +This package will bootstrap the internal components for you, using SimpleInjector v5
https://docs.simpleinjector.org/en/5.0/

2022-11-04 15:38 UTC, msalak-scia commented
Thank you @dschuermans for the detailed requests. They should be hopefully all solved. I also added the link to nuget.org for every package, is it ok or does it just make it more complicated :D?

2022-11-07 09:26 UTC, dschuermans approved these changes

2022-11-07 09:27 UTC, merged