Enhancement/242 sdk names too long
StructuralAnalysisFormat/StructuralAnalysisFormat-Doc pull request #244
Opened 2022-11-15 11:48 UTC by msalak-scia

changing the names of the pages for the 4 SDK packages. They were named according to the name of the package, but the name is too long to fit in the left side menu panel. 

They were changed to fit.

closes #242

2022-11-15 14:04 UTC, msalak-scia commented
@dschuermans  what do you think? Should I maybe put Simple Injector together as one word? What about Bootstrappers is it supposed to be with or without an s at the end?

2022-11-15 18:17 UTC, dschuermans requested changes
Please make these adjustments

Finally, could you also re-order the items?

![image](https://user-images.githubusercontent.com/6634696/201995737-4c5a6037-6152-4130-8d84-aa3d3904e703.png)

2022-11-15 18:17 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Bootstrappers.SimpleInjector4.md
> +# Bootstrappers Simple Injector 4
I'd call this "Bootstrapping: SimpleInjector 4"

2022-11-15 18:17 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Bootstrappers.SimpleInjector5.md
> +# Bootstrappers Simple Injector 5
I'd call this "Bootstrapping: SimpleInjector 5"

2022-11-15 18:17 UTC, dschuermans commented on docs/SDK/StructuralAnalysisFormat.Tests.Infrastructure.md
> +# Tests Infrastructure
I'd call this "Testing"

2022-11-21 09:32 UTC, msalak-scia commented
I changed the names, changed the order and changed the description in introduction a little

2022-11-22 08:47 UTC, dschuermans approved these changes

2022-11-24 07:40 UTC, merged