Feature/286 nonlinear relconnectssurfaceedge
StructuralAnalysisFormat/StructuralAnalysisFormat-Doc pull request #287
Opened 2023-03-27 08:46 UTC by msalak-scia

This extends the RelConnectsSurfaceEdge with nonlinear behavior of the hinges. Simillarly to the changes previously done on RelConnectsStructuralMember.

There are also two unrelated small things
- one typo in StructuralProxyElement
- fixed link to released docs

closes #286

2023-03-27 09:02 UTC, msalak-scia commented on docs/structural-analysis-elements/structuralproxyelement.md
unrelated - only fixing mistakes that were there

2023-03-27 09:03 UTC, msalak-scia commented on docs/supports-and-hinges/relconnectsstructuralmember.md
I extended
- description
- requirement for stiffness which I previously forgot to update
- tiny graphical change in notes

2023-03-27 09:04 UTC, msalak-scia commented on docs/supports-and-hinges/relconnectssurfaceedge.md
These are the main changes

2023-04-03 07:13 UTC, dschuermans requested changes
Fix the typo's :)

2023-04-03 07:13 UTC, dschuermans commented on docs/supports-and-hinges/relconnectssurfaceedge.md
> +| Function fiz | String | Nonlin fun 2 | yes, if fiz = Nonlinear | Reference to object [NonlinearFunction](../supports-and-hinges/nonlinearfunction.md). Nonlinear function must be of type Rotation |
Something i've overlooked in the previous PR too, the 

> Nonlinear function must be of type Translation
or
> Nonlinear function must be of type Rotation

is something we currently can't easily validate in the SDK...

2023-04-03 08:49 UTC, MartinSalak commented on docs/getting-started/release-notes.md
> +   * new porperties added: Function ux, Function uy, Function, uz, Function fix, Function fiy, Function fiz
fixed

2023-04-03 08:50 UTC, MartinSalak commented on docs/getting-started/release-notes.md
>     * new porperties added: Function ux, Function uy, Function, uz, Function fix, Function fiy, Function fiz
fixed

2023-04-03 08:50 UTC, MartinSalak commented on docs/structural-analysis-elements/structuralproxyelement.md
> +StrucutralProxyElements are solid objects described by their boundary representation (faces of objects). The common use for StrucutralProxyElements can be found for complex part of structures (garage
There were a lot of them, I hope I got all.

2023-04-03 09:16 UTC, dschuermans commented on docs/supports-and-hinges/relconnectssurfaceedge.md
> +| Function fiz | String | Nonlin fun 2 | yes, if fiz = Nonlinear | Reference to object [NonlinearFunction](../supports-and-hinges/nonlinearfunction.md). Nonlinear function must be of type Rotation |
We'll look at adding some kind of validation to the SDK

2023-04-03 13:56 UTC, merged